### record medication details for animal

POST http://localhost:8085/api/medication
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "tagNumber": "K01-001",
  "type": "VACCINATION",
  "drugName": "Oxytocin",
  "dosage": "100ml * 2 ",
  "administeredBy": "John Bwete",
  "administeredAt": ""
}

###