spring.application.name=animal-registry-service

server.port=8080


spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admin_user
spring.datasource.password=password
spring.datasource.url=jdbc:postgresql://localhost:5050/postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer