spring.application.name=animal-registry-service

server.port=8088


spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=developer
spring.datasource.password=password
spring.datasource.url=jdbc:postgresql://localhost:5000/ranzo
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
