### GET request to example server
POST http://localhost:8080/animals
Content-Type: application/json

{
  "tagNumber": "KO2-015",
  "species": "COW",
  "breed": "Ankole",
  "gender": "Female",
  "status": "ALIVE",
  "kraalAssignment": "Kraal 2",
  "birthdate": "2023-08-23",
  "registeredOn": "",
  "updatedOn": ""
}

###