spring.application.name=ranzo

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.url=jdbc:postgresql://localhost:5050/postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect