spring.application.name=ranzo

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=user
spring.datasource.password=secret
spring.datasource.url=jdbc:postgresql://localhost:5050/db
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=w3yK/mAFqK2NFWymzcXJXSvrSK94HvWdjZajWNlnIxY=